---
- name: Configure standard ACL
  hosts: R2
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: Load new ACL into device
     ios_config:
       command: ip access-list extended REQ1
       lines:
         - 10 deny tcp any any eq telnet
         - 20 permit ip any any
         - deny any
